apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::952007629372:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-PW6AM2EG559F
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::952007629372:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-10T03:16:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1664"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: b60f1af6-51f6-4549-867d-d15441e619fd
